### create user

POST https://user-management-app-2xge.onrender.com/user-api/users
Content-Type: application/json

{
    "name":"ab",
    "email":"abcd@gmail.com",
    "dateOfBirth":"2005-1-1",
    "mobileNumber":1234567
}

### read all users
GET https://user-management-app-2xge.onrender.com/user-api/users


###read a user by id
GET https://user-management-app-2xge.onrender.com/user-api/users/69a68f8d95416eee05d274f6


###
PUT https://user-management-app-2xge.onrender.com/user-api/users/69a68f8d95416eee05d274f6

###
PATCH  https://user-management-app-2xge.onrender.com/user-api/users/69a68f8d95416eee05d274f6