### create user

POST http://localhost:4000/user-api/users
Content-Type: application/json

{
    "name":"ab",
    "email":"abcd@gmail.com",
    "dateOfBirth":"2005-1-1",
    "mobileNumber":1234567
}

### read all users
GET http://localhost:4000/user-api/users


###read a user by id
GET http://localhost:4000/user-api/users/69a68f8d95416eee05d274f6


###
PUT http://localhost:4000/user-api/users/69a68f8d95416eee05d274f6

###
PATCH  http://localhost:4000/user-api/users/69a68f8d95416eee05d274f6